name: backupz2
base: core18
version: '1.0.0'
summary: Create backup tar.gz archive
description: |
  Create backup tar.gz archive in multiple processes and send to ftp or save to folder.
grade: stable
confinement: strict

parts:
  backupz2:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - click
      - pyYaml
    stage-packages:
      - pigz
      - tar

  backupz2-run:
    plugin: dump
    source: scripts
    organize:
      run.sh: bin/

apps:
  backupz2:
    command: bin/run.sh
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    plugs:
      - home
